name: Toy

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [gcc-12, clang-15]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          if [[ "${{ matrix.compiler }}" == gcc-12 ]]; then
            sudo apt-get install -y gcc-12 g++-12
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 90
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 90
          else
            sudo apt-get install -y clang-15
            sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 90
            sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 90
          fi

      - name: Configure CMake GCC
        if: matrix.compiler == 'gcc-12'
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_BUILD_TYPE=Release

      - name: Configure CMake Clang
        if: matrix.compiler == 'clang-15'
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_C_COMPILER=clang-15 -DCMAKE_CXX_COMPILER=clang++-15 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          cmake --build . --parallel $(nproc)

  windows-msvc-build:
    name: Windows (MSVC)
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # CMake 工具链配置
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded `
            -DCMAKE_CXX_FLAGS_RELEASE="/O2 /Ob2 /fp:fast"

      - name: Build
        run: |
          cd build
          cmake --build . --config Release --parallel 4

  macos-build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          cmake --build . --parallel $(sysctl -n hw.logicalcpu)
